theme: jekyll-theme-cayman
title: Ugnė Dudzevičiūtė
description: Postdoctoral Fellow at MPIA
<img src="jcmt2.jpg" alt="A round image" width="150" height="150" style="border-radius: 50%; float: right; margin-left: 10px;" />
